namespace POC.ImageConverter
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up resources being used.
        /// </summary>
        /// <param name="disposing">true if it is necessary to dispose of managed resources; otherwise false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by Windows Form Designer

        /// <summary>
        /// Required method for Designer support - do not modify the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            this.groupBoxConfigurations = new System.Windows.Forms.GroupBox();
            this.groupBoxThirdStep = new System.Windows.Forms.GroupBox();
            this.buttonConvertImage = new System.Windows.Forms.Button();
            this.groupBoxSecondStep = new System.Windows.Forms.GroupBox();
            this.radioEXIF = new System.Windows.Forms.RadioButton();
            this.radioICON = new System.Windows.Forms.RadioButton();
            this.radioGIF = new System.Windows.Forms.RadioButton();
            this.radioPNG = new System.Windows.Forms.RadioButton();
            this.radioBMP = new System.Windows.Forms.RadioButton();
            this.radioJPG = new System.Windows.Forms.RadioButton();
            this.groupBoxFirstStep = new System.Windows.Forms.GroupBox();
            this.buttonChooseImage = new System.Windows.Forms.Button();
            this.groupBoxChosenImage = new System.Windows.Forms.GroupBox();
            this.pictureBoxChosenImage = new System.Windows.Forms.PictureBox();
            this.openFileDialog = new System.Windows.Forms.OpenFileDialog();
            this.saveFileDialog = new System.Windows.Forms.SaveFileDialog();
            this.groupBoxConfigurations.SuspendLayout();
            this.groupBoxThirdStep.SuspendLayout();
            this.groupBoxSecondStep.SuspendLayout();
            this.groupBoxFirstStep.SuspendLayout();
            this.groupBoxChosenImage.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxChosenImage)).BeginInit();
            this.SuspendLayout();
            // 
            // groupBoxConfigurations
            // 
            this.groupBoxConfigurations.Controls.Add(this.groupBoxThirdStep);
            this.groupBoxConfigurations.Controls.Add(this.groupBoxSecondStep);
            this.groupBoxConfigurations.Controls.Add(this.groupBoxFirstStep);
            this.groupBoxConfigurations.Location = new System.Drawing.Point(13, 13);
            this.groupBoxConfigurations.Name = "groupBoxConfigurations";
            this.groupBoxConfigurations.Size = new System.Drawing.Size(248, 529);
            this.groupBoxConfigurations.TabIndex = 0;
            this.groupBoxConfigurations.TabStop = false;
            this.groupBoxConfigurations.Text = "Configurations";
            // 
            // groupBoxThirdStep
            // 
            this.groupBoxThirdStep.Controls.Add(this.buttonConvertImage);
            this.groupBoxThirdStep.Location = new System.Drawing.Point(7, 402);
            this.groupBoxThirdStep.Name = "groupBoxThirdStep";
            this.groupBoxThirdStep.Size = new System.Drawing.Size(235, 100);
            this.groupBoxThirdStep.TabIndex = 2;
            this.groupBoxThirdStep.TabStop = false;
            this.groupBoxThirdStep.Text = "Third Step";
            // 
            // buttonConvertImage
            // 
            this.buttonConvertImage.Location = new System.Drawing.Point(23, 28);
            this.buttonConvertImage.Name = "buttonConvertImage";
            this.buttonConvertImage.Size = new System.Drawing.Size(193, 52);
            this.buttonConvertImage.TabIndex = 1;
            this.buttonConvertImage.Text = "Convert Image";
            this.buttonConvertImage.UseVisualStyleBackColor = true;
            this.buttonConvertImage.Click += new System.EventHandler(this.BtnConvertImage_Click);
            // 
            // groupBoxSecondStep
            // 
            this.groupBoxSecondStep.Controls.Add(this.radioEXIF);
            this.groupBoxSecondStep.Controls.Add(this.radioICON);
            this.groupBoxSecondStep.Controls.Add(this.radioGIF);
            this.groupBoxSecondStep.Controls.Add(this.radioPNG);
            this.groupBoxSecondStep.Controls.Add(this.radioBMP);
            this.groupBoxSecondStep.Controls.Add(this.radioJPG);
            this.groupBoxSecondStep.Location = new System.Drawing.Point(7, 175);
            this.groupBoxSecondStep.Name = "groupBoxSecondStep";
            this.groupBoxSecondStep.Size = new System.Drawing.Size(235, 176);
            this.groupBoxSecondStep.TabIndex = 1;
            this.groupBoxSecondStep.TabStop = false;
            this.groupBoxSecondStep.Text = "Second Step";
            // 
            // radioEXIF
            // 
            this.radioEXIF.AutoSize = true;
            this.radioEXIF.Location = new System.Drawing.Point(23, 146);
            this.radioEXIF.Name = "radioEXIF";
            this.radioEXIF.Size = new System.Drawing.Size(51, 17);
            this.radioEXIF.TabIndex = 3;
            this.radioEXIF.TabStop = true;
            this.radioEXIF.Text = ".EXIF";
            this.radioEXIF.UseVisualStyleBackColor = true;
            // 
            // radioICON
            // 
            this.radioICON.AutoSize = true;
            this.radioICON.Location = new System.Drawing.Point(23, 100);
            this.radioICON.Name = "radioICON";
            this.radioICON.Size = new System.Drawing.Size(54, 17);
            this.radioICON.TabIndex = 4;
            this.radioICON.TabStop = true;
            this.radioICON.Text = ".ICON";
            this.radioICON.UseVisualStyleBackColor = true;
            // 
            // radioGIF
            // 
            this.radioGIF.AutoSize = true;
            this.radioGIF.Location = new System.Drawing.Point(23, 123);
            this.radioGIF.Name = "radioGIF";
            this.radioGIF.Size = new System.Drawing.Size(45, 17);
            this.radioGIF.TabIndex = 5;
            this.radioGIF.TabStop = true;
            this.radioGIF.Text = ".GIF";
            this.radioGIF.UseVisualStyleBackColor = true;
            // 
            // radioPNG
            // 
            this.radioPNG.AutoSize = true;
            this.radioPNG.Location = new System.Drawing.Point(23, 54);
            this.radioPNG.Name = "radioPNG";
            this.radioPNG.Size = new System.Drawing.Size(51, 17);
            this.radioPNG.TabIndex = 6;
            this.radioPNG.TabStop = true;
            this.radioPNG.Text = ".PNG";
            this.radioPNG.UseVisualStyleBackColor = true;
            // 
            // radioBMP
            // 
            this.radioBMP.AutoSize = true;
            this.radioBMP.Location = new System.Drawing.Point(23, 77);
            this.radioBMP.Name = "radioBMP";
            this.radioBMP.Size = new System.Drawing.Size(51, 17);
            this.radioBMP.TabIndex = 7;
            this.radioBMP.TabStop = true;
            this.radioBMP.Text = ".BMP";
            this.radioBMP.UseVisualStyleBackColor = true;
            // 
            // radioJPG
            // 
            this.radioJPG.AutoSize = true;
            this.radioJPG.Location = new System.Drawing.Point(23, 31);
            this.radioJPG.Name = "radioJPG";
            this.radioJPG.Size = new System.Drawing.Size(48, 17);
            this.radioJPG.TabIndex = 8;
            this.radioJPG.TabStop = true;
            this.radioJPG.Text = ".JPG";
            this.radioJPG.UseVisualStyleBackColor = true;
            // 
            // groupBoxFirstStep
            // 
            this.groupBoxFirstStep.Controls.Add(this.buttonChooseImage);
            this.groupBoxFirstStep.Location = new System.Drawing.Point(7, 39);
            this.groupBoxFirstStep.Name = "groupBoxFirstStep";
            this.groupBoxFirstStep.Size = new System.Drawing.Size(235, 100);
            this.groupBoxFirstStep.TabIndex = 0;
            this.groupBoxFirstStep.TabStop = false;
            this.groupBoxFirstStep.Text = "First Step";
            // 
            // buttonChooseImage
            // 
            this.buttonChooseImage.Location = new System.Drawing.Point(23, 28);
            this.buttonChooseImage.Name = "buttonChooseImage";
            this.buttonChooseImage.Size = new System.Drawing.Size(193, 52);
            this.buttonChooseImage.TabIndex = 0;
            this.buttonChooseImage.Text = "Choose Image";
            this.buttonChooseImage.UseVisualStyleBackColor = true;
            this.buttonChooseImage.Click += new System.EventHandler(this.BtnChooseImage_Click);
            // 
            // groupBoxChosenImage
            // 
            this.groupBoxChosenImage.Controls.Add(this.pictureBoxChosenImage);
            this.groupBoxChosenImage.Location = new System.Drawing.Point(280, 13);
            this.groupBoxChosenImage.Name = "groupBoxChosenImage";
            this.groupBoxChosenImage.Size = new System.Drawing.Size(508, 529);
            this.groupBoxChosenImage.TabIndex = 1;
            this.groupBoxChosenImage.TabStop = false;
            this.groupBoxChosenImage.Text = "Chosen Image";
            // 
            // pictureBoxChosenImage
            // 
            this.pictureBoxChosenImage.Location = new System.Drawing.Point(18, 30);
            this.pictureBoxChosenImage.Name = "pictureBoxChosenImage";
            this.pictureBoxChosenImage.Size = new System.Drawing.Size(470, 480);
            this.pictureBoxChosenImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBoxChosenImage.TabIndex = 0;
            this.pictureBoxChosenImage.TabStop = false;
            // 
            // openFileDialog
            // 
            this.openFileDialog.FileName = "openFileDialog1";
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 554);
            this.Controls.Add(this.groupBoxChosenImage);
            this.Controls.Add(this.groupBoxConfigurations);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "Form1";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Image Converter";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.groupBoxConfigurations.ResumeLayout(false);
            this.groupBoxThirdStep.ResumeLayout(false);
            this.groupBoxSecondStep.ResumeLayout(false);
            this.groupBoxSecondStep.PerformLayout();
            this.groupBoxFirstStep.ResumeLayout(false);
            this.groupBoxChosenImage.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxChosenImage)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.GroupBox groupBoxConfigurations;
        private System.Windows.Forms.GroupBox groupBoxThirdStep;
        private System.Windows.Forms.GroupBox groupBoxSecondStep;
        private System.Windows.Forms.GroupBox groupBoxFirstStep;
        private System.Windows.Forms.Button buttonConvertImage;
        private System.Windows.Forms.Button buttonChooseImage;
        private System.Windows.Forms.RadioButton radioEXIF;
        private System.Windows.Forms.RadioButton radioICON;
        private System.Windows.Forms.RadioButton radioGIF;
        private System.Windows.Forms.RadioButton radioPNG;
        private System.Windows.Forms.RadioButton radioBMP;
        private System.Windows.Forms.RadioButton radioJPG;
        private System.Windows.Forms.GroupBox groupBoxChosenImage;
        private System.Windows.Forms.PictureBox pictureBoxChosenImage;
        private System.Windows.Forms.OpenFileDialog openFileDialog;
        private System.Windows.Forms.SaveFileDialog saveFileDialog;
    }
}